// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drafts.sql

package sleeperdb

import (
	"context"
	"database/sql"
	"time"
)

const listDraftPicksByLeague = `-- name: ListDraftPicksByLeague :many
SELECT
    d.id, d.league_id, d.draft_id, d.team_id, d.player_id, d.overall_pick, d.round_num, d.round_pick, d.draft_slot, d.picked_by, d.keeper_status, d.created_at,
    t.roster_id,
    t.team_name,
    p.sleeper_id,
    p.espn_id,
    p.name AS player_name,
    p.position
FROM drafts d
JOIN teams t ON t.id = d.team_id
JOIN players p ON p.id = d.player_id
WHERE d.league_id = $1
ORDER BY d.overall_pick ASC
`

type ListDraftPicksByLeagueRow struct {
	ID           int64          `json:"id"`
	LeagueID     int64          `json:"league_id"`
	DraftID      string         `json:"draft_id"`
	TeamID       int64          `json:"team_id"`
	PlayerID     int64          `json:"player_id"`
	OverallPick  int32          `json:"overall_pick"`
	RoundNum     int32          `json:"round_num"`
	RoundPick    int32          `json:"round_pick"`
	DraftSlot    sql.NullInt32  `json:"draft_slot"`
	PickedBy     sql.NullString `json:"picked_by"`
	KeeperStatus bool           `json:"keeper_status"`
	CreatedAt    time.Time      `json:"created_at"`
	RosterID     int32          `json:"roster_id"`
	TeamName     string         `json:"team_name"`
	SleeperID    string         `json:"sleeper_id"`
	EspnID       sql.NullString `json:"espn_id"`
	PlayerName   string         `json:"player_name"`
	Position     sql.NullString `json:"position"`
}

func (q *Queries) ListDraftPicksByLeague(ctx context.Context, leagueID int64) ([]ListDraftPicksByLeagueRow, error) {
	rows, err := q.db.QueryContext(ctx, listDraftPicksByLeague, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftPicksByLeagueRow
	for rows.Next() {
		var i ListDraftPicksByLeagueRow
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.DraftID,
			&i.TeamID,
			&i.PlayerID,
			&i.OverallPick,
			&i.RoundNum,
			&i.RoundPick,
			&i.DraftSlot,
			&i.PickedBy,
			&i.KeeperStatus,
			&i.CreatedAt,
			&i.RosterID,
			&i.TeamName,
			&i.SleeperID,
			&i.EspnID,
			&i.PlayerName,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
