// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leagues.sql

package sleeperdb

import (
	"context"
)

const getLeagueByID = `-- name: GetLeagueByID :one
SELECT id, sleeper_league_id, previous_league_id, canonical_league_id, season, name, status, sport, total_rosters, draft_id, avatar, roster_positions, scoring_settings, league_settings, created_at, updated_at FROM leagues
WHERE id = $1
`

func (q *Queries) GetLeagueByID(ctx context.Context, id int64) (League, error) {
	row := q.db.QueryRowContext(ctx, getLeagueByID, id)
	var i League
	err := row.Scan(
		&i.ID,
		&i.SleeperLeagueID,
		&i.PreviousLeagueID,
		&i.CanonicalLeagueID,
		&i.Season,
		&i.Name,
		&i.Status,
		&i.Sport,
		&i.TotalRosters,
		&i.DraftID,
		&i.Avatar,
		&i.RosterPositions,
		&i.ScoringSettings,
		&i.LeagueSettings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeagueBySleeperID = `-- name: GetLeagueBySleeperID :one
SELECT id, sleeper_league_id, previous_league_id, canonical_league_id, season, name, status, sport, total_rosters, draft_id, avatar, roster_positions, scoring_settings, league_settings, created_at, updated_at FROM leagues
WHERE sleeper_league_id = $1
`

func (q *Queries) GetLeagueBySleeperID(ctx context.Context, sleeperLeagueID string) (League, error) {
	row := q.db.QueryRowContext(ctx, getLeagueBySleeperID, sleeperLeagueID)
	var i League
	err := row.Scan(
		&i.ID,
		&i.SleeperLeagueID,
		&i.PreviousLeagueID,
		&i.CanonicalLeagueID,
		&i.Season,
		&i.Name,
		&i.Status,
		&i.Sport,
		&i.TotalRosters,
		&i.DraftID,
		&i.Avatar,
		&i.RosterPositions,
		&i.ScoringSettings,
		&i.LeagueSettings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLeagues = `-- name: ListLeagues :many
SELECT id, sleeper_league_id, previous_league_id, canonical_league_id, season, name, status, sport, total_rosters, draft_id, avatar, roster_positions, scoring_settings, league_settings, created_at, updated_at FROM leagues
ORDER BY season ASC, name ASC
`

func (q *Queries) ListLeagues(ctx context.Context) ([]League, error) {
	rows, err := q.db.QueryContext(ctx, listLeagues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []League
	for rows.Next() {
		var i League
		if err := rows.Scan(
			&i.ID,
			&i.SleeperLeagueID,
			&i.PreviousLeagueID,
			&i.CanonicalLeagueID,
			&i.Season,
			&i.Name,
			&i.Status,
			&i.Sport,
			&i.TotalRosters,
			&i.DraftID,
			&i.Avatar,
			&i.RosterPositions,
			&i.ScoringSettings,
			&i.LeagueSettings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaguesBySeason = `-- name: ListLeaguesBySeason :many
SELECT id, sleeper_league_id, previous_league_id, canonical_league_id, season, name, status, sport, total_rosters, draft_id, avatar, roster_positions, scoring_settings, league_settings, created_at, updated_at FROM leagues
WHERE season = $1
ORDER BY name ASC
`

func (q *Queries) ListLeaguesBySeason(ctx context.Context, season int32) ([]League, error) {
	rows, err := q.db.QueryContext(ctx, listLeaguesBySeason, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []League
	for rows.Next() {
		var i League
		if err := rows.Scan(
			&i.ID,
			&i.SleeperLeagueID,
			&i.PreviousLeagueID,
			&i.CanonicalLeagueID,
			&i.Season,
			&i.Name,
			&i.Status,
			&i.Sport,
			&i.TotalRosters,
			&i.DraftID,
			&i.Avatar,
			&i.RosterPositions,
			&i.ScoringSettings,
			&i.LeagueSettings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
