// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matchups.sql

package sleeperdb

import (
	"context"
)

const listMatchupsByLeague = `-- name: ListMatchupsByLeague :many
SELECT id, league_id, week, matchup_id, roster_id, opponent_roster_id, points, custom_points, is_playoff, matchup_type, starters, players FROM matchups
WHERE league_id = $1
ORDER BY week ASC, matchup_id ASC, roster_id ASC
`

func (q *Queries) ListMatchupsByLeague(ctx context.Context, leagueID int64) ([]Matchup, error) {
	rows, err := q.db.QueryContext(ctx, listMatchupsByLeague, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Matchup
	for rows.Next() {
		var i Matchup
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.Week,
			&i.MatchupID,
			&i.RosterID,
			&i.OpponentRosterID,
			&i.Points,
			&i.CustomPoints,
			&i.IsPlayoff,
			&i.MatchupType,
			&i.Starters,
			&i.Players,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
