// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playoff_brackets.sql

package sleeperdb

import (
	"context"
)

const listPlayoffBracketMatchupsByLeague = `-- name: ListPlayoffBracketMatchupsByLeague :many
SELECT id, league_id, bracket_type, round_num, matchup_id, placement, slot1_roster_id, slot2_roster_id, slot1_source_matchup_id, slot1_source_result, slot2_source_matchup_id, slot2_source_result, winner_roster_id, loser_roster_id, raw_payload FROM playoff_bracket_matchups
WHERE league_id = $1
ORDER BY bracket_type ASC, round_num ASC, matchup_id ASC
`

func (q *Queries) ListPlayoffBracketMatchupsByLeague(ctx context.Context, leagueID int64) ([]PlayoffBracketMatchup, error) {
	rows, err := q.db.QueryContext(ctx, listPlayoffBracketMatchupsByLeague, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayoffBracketMatchup
	for rows.Next() {
		var i PlayoffBracketMatchup
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.BracketType,
			&i.RoundNum,
			&i.MatchupID,
			&i.Placement,
			&i.Slot1RosterID,
			&i.Slot2RosterID,
			&i.Slot1SourceMatchupID,
			&i.Slot1SourceResult,
			&i.Slot2SourceMatchupID,
			&i.Slot2SourceResult,
			&i.WinnerRosterID,
			&i.LoserRosterID,
			&i.RawPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
