// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rosters.sql

package sleeperdb

import (
	"context"
	"database/sql"
)

const listRosterEntriesByLeagueAndWeek = `-- name: ListRosterEntriesByLeagueAndWeek :many
SELECT
    r.id, r.league_id, r.week, r.roster_id, r.player_id, r.roster_slot, r.is_starter,
    p.sleeper_id,
    p.espn_id,
    p.name AS player_name,
    p.position
FROM rosters r
JOIN players p ON p.id = r.player_id
WHERE r.league_id = $1
  AND r.week = $2
ORDER BY r.roster_id ASC, r.is_starter DESC, p.name ASC
`

type ListRosterEntriesByLeagueAndWeekParams struct {
	LeagueID int64 `json:"league_id"`
	Week     int32 `json:"week"`
}

type ListRosterEntriesByLeagueAndWeekRow struct {
	ID         int64          `json:"id"`
	LeagueID   int64          `json:"league_id"`
	Week       int32          `json:"week"`
	RosterID   int32          `json:"roster_id"`
	PlayerID   int64          `json:"player_id"`
	RosterSlot string         `json:"roster_slot"`
	IsStarter  bool           `json:"is_starter"`
	SleeperID  string         `json:"sleeper_id"`
	EspnID     sql.NullString `json:"espn_id"`
	PlayerName string         `json:"player_name"`
	Position   sql.NullString `json:"position"`
}

func (q *Queries) ListRosterEntriesByLeagueAndWeek(ctx context.Context, arg ListRosterEntriesByLeagueAndWeekParams) ([]ListRosterEntriesByLeagueAndWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listRosterEntriesByLeagueAndWeek, arg.LeagueID, arg.Week)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRosterEntriesByLeagueAndWeekRow
	for rows.Next() {
		var i ListRosterEntriesByLeagueAndWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.Week,
			&i.RosterID,
			&i.PlayerID,
			&i.RosterSlot,
			&i.IsStarter,
			&i.SleeperID,
			&i.EspnID,
			&i.PlayerName,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
