// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Draft struct {
	ID               int32         `json:"id"`
	TeamID           int32         `json:"team_id"`
	PlayerID         int32         `json:"player_id"`
	OverallPick      int32         `json:"overallPick"`
	RoundNum         int32         `json:"roundNum"`
	RoundPick        int32         `json:"roundPick"`
	KeeperStatus     bool          `json:"keeperStatus"`
	BidAmount        int32         `json:"bidAmount"`
	NominatingTeamID sql.NullInt32 `json:"nominating_team_id"`
}

type League struct {
	ID          int32 `json:"id"`
	LeagueId    int32 `json:"leagueId"`
	Year        int32 `json:"year"`
	TeamCount   int32 `json:"teamCount"`
	CurrentWeek int32 `json:"currentWeek"`
	NflWeek     int32 `json:"nflWeek"`
}

type Matchup struct {
	ID          int32         `json:"id"`
	Week        int32         `json:"week"`
	HomeTeamID  sql.NullInt32 `json:"home_team_id"`
	AwayTeamID  sql.NullInt32 `json:"away_team_id"`
	HomeScore   float64       `json:"homeScore"`
	AwayScore   float64       `json:"awayScore"`
	IsPlayoff   bool          `json:"isPlayoff"`
	MatchupType string        `json:"matchupType"`
}

type Player struct {
	ID       int32          `json:"id"`
	EspnId   int32          `json:"espnId"`
	Name     string         `json:"name"`
	Position sql.NullString `json:"position"`
}

type Team struct {
	ID                     int32  `json:"id"`
	LeagueID               int32  `json:"league_id"`
	TeamId                 int32  `json:"teamId"`
	Year                   int32  `json:"year"`
	TeamAbbrv              string `json:"teamAbbrv"`
	TeamName               string `json:"teamName"`
	Owners                 string `json:"owners"`
	DivisionId             string `json:"divisionId"`
	DivisionName           string `json:"divisionName"`
	Wins                   int32  `json:"wins"`
	Losses                 int32  `json:"losses"`
	Ties                   int32  `json:"ties"`
	PointsFor              int32  `json:"pointsFor"`
	PointsAgainst          int32  `json:"pointsAgainst"`
	WaiverRank             int32  `json:"waiverRank"`
	Acquisitions           int32  `json:"acquisitions"`
	AcquisitionBudgetSpent int32  `json:"acquisitionBudgetSpent"`
	Drops                  int32  `json:"drops"`
	Trades                 int32  `json:"trades"`
	StreakType             string `json:"streakType"`
	StreakLength           int32  `json:"streakLength"`
	Standing               int32  `json:"standing"`
	FinalStanding          int32  `json:"finalStanding"`
	DraftProjRank          int32  `json:"draftProjRank"`
	PlayoffPct             int32  `json:"playoffPct"`
	LogoUrl                string `json:"logoUrl"`
}

type Token struct {
	Hash   []byte    `json:"hash"`
	UserID int64     `json:"user_id"`
	Expiry time.Time `json:"expiry"`
	Scope  string    `json:"scope"`
}

type User struct {
	ID           int64     `json:"id"`
	CreatedAt    time.Time `json:"created_at"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"password_hash"`
	Activated    bool      `json:"activated"`
	Version      int32     `json:"version"`
}
